services:


  redis:
    image: redis/redis-stack:latest
    container_name: redis-json
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data


networks:
  app-network:
    driver: bridge
